// lib/features/grades/data/models/grade_model.dart
import 'package:flutter/foundation.dart';
import '../../domain/entities/grade_entity.dart';

/// Model untuk Grade dengan serialization
class GradeModel extends GradeEntity {
  const GradeModel({
    required super.id,
    required super.studentId,
    required super.classId,
    required super.itemId,
    required super.itemType,
    required super.score,
    required super.maxScore,
    required super.percentage,
    required super.recordedAt,
    super.itemTitle,
    super.className,
  });

  /// Create from JSON (Supabase response)
  factory GradeModel.fromJson(Map<String, dynamic> json) {
    // Handle nested class data for class name
    String? className;
    if (json['classes'] != null) {
      className = json['classes']['name'];
    }

    return GradeModel(
      id: json['id']?.toString() ?? '',
      studentId: json['student_id']?.toString() ?? '',
      classId: json['class_id']?.toString() ?? '',
      itemId: json['item_id']?.toString() ?? '',
      itemType: json['item_type'] ?? 'quiz',
      score: (json['score'] ?? 0).toDouble(),
      maxScore: (json['max_score'] ?? 100).toDouble(),
      percentage: (json['percentage'] ?? 0).toDouble(),
      recordedAt: _parseDateTime(json['recorded_at']) ?? DateTime.now(),
      itemTitle: json['item_title'],
      className: className,
    );
  }

  /// Create from quiz attempt
  factory GradeModel.fromQuizAttempt({
    required String studentId,
    required String classId,
    required String quizId,
    required double score,
    required double maxScore,
    String? quizTitle,
  }) {
    final percentage = maxScore > 0 ? (score / maxScore) * 100 : 0.0;
    return GradeModel(
      id: '', // Will be generated by Supabase
      studentId: studentId,
      classId: classId,
      itemId: quizId,
      itemType: 'quiz',
      score: score,
      maxScore: maxScore,
      percentage: percentage,
      recordedAt: DateTime.now(),
      itemTitle: quizTitle,
    );
  }

  /// Create from assignment submission
  factory GradeModel.fromSubmission({
    required String studentId,
    required String classId,
    required String assignmentId,
    required double score,
    required double maxScore,
    String? assignmentTitle,
  }) {
    final percentage = maxScore > 0 ? (score / maxScore) * 100 : 0.0;
    return GradeModel(
      id: '', // Will be generated by Supabase
      studentId: studentId,
      classId: classId,
      itemId: assignmentId,
      itemType: 'assignment',
      score: score,
      maxScore: maxScore,
      percentage: percentage,
      recordedAt: DateTime.now(),
      itemTitle: assignmentTitle,
    );
  }

  /// Convert to JSON for Supabase
  Map<String, dynamic> toJson() => {
        'id': id,
        'student_id': studentId,
        'class_id': classId,
        'item_id': itemId,
        'item_type': itemType,
        'score': score,
        'max_score': maxScore,
        'percentage': percentage,
        'recorded_at': _formatDateTimeForSupabase(recordedAt),
      };

  /// Convert to JSON for creating new grade (without id)
  Map<String, dynamic> toCreateJson() => {
        'student_id': studentId,
        'class_id': classId,
        'item_id': itemId,
        'item_type': itemType,
        'score': score,
        'max_score': maxScore,
        'percentage': percentage,
        'recorded_at': _formatDateTimeForSupabase(recordedAt),
      };

  /// Convert to JSON for updating grade
  Map<String, dynamic> toUpdateJson() => {
        'score': score,
        'max_score': maxScore,
        'percentage': percentage,
        'recorded_at': _formatDateTimeForSupabase(recordedAt),
      };

  @override
  GradeModel copyWith({
    String? id,
    String? studentId,
    String? classId,
    String? itemId,
    String? itemType,
    double? score,
    double? maxScore,
    double? percentage,
    DateTime? recordedAt,
    String? itemTitle,
    String? className,
  }) {
    return GradeModel(
      id: id ?? this.id,
      studentId: studentId ?? this.studentId,
      classId: classId ?? this.classId,
      itemId: itemId ?? this.itemId,
      itemType: itemType ?? this.itemType,
      score: score ?? this.score,
      maxScore: maxScore ?? this.maxScore,
      percentage: percentage ?? this.percentage,
      recordedAt: recordedAt ?? this.recordedAt,
      itemTitle: itemTitle ?? this.itemTitle,
      className: className ?? this.className,
    );
  }
}

/// Helper function untuk parse DateTime dari Supabase
DateTime? _parseDateTime(String? dateString) {
  if (dateString == null || dateString.isEmpty) return null;
  try {
    final parsed = DateTime.tryParse(dateString);
    if (parsed == null) return null;
    if (parsed.isUtc) {
      return parsed.toLocal();
    }
    return parsed;
  } catch (e) {
    debugPrint('Error parsing DateTime: $dateString - $e');
    return null;
  }
}

/// Helper function untuk format DateTime ke ISO8601 string untuk Supabase
String? _formatDateTimeForSupabase(DateTime? dateTime) {
  if (dateTime == null) return null;
  return dateTime.toUtc().toIso8601String();
}
